package constants

var QuestionIndexIdField string = "question_id"

var IndexEndpoint string = "/indexcontent/question"

var IndexAppName string = "doc-indexing-api"

var LatexMap = map[string]string{
	`\alpha`:                `α`,
	`\Alpha`:                `Α`,
	`\beta`:                 `β`,
	`\Beta`:                 `Β`,
	`\gamma`:                `γ`,
	`\Gamma`:                `Γ`,
	`\delta`:                `δ`,
	`\Delta`:                `Δ`,
	`\epsilon`:              `ε`,
	`\Epsilon`:              `Ε`,
	`\zeta`:                 `ζ`,
	`\Zeta`:                 `Ζ`,
	`\eta`:                  `η`,
	`\Eta`:                  `Η`,
	`\theta`:                `θ`,
	`\Theta`:                `Θ`,
	`\iota`:                 `ι`,
	`\Iota`:                 `Ι`,
	`\kappa`:                `κ`,
	`\Kappa`:                `Κ`,
	`\lambda`:               `λ`,
	`\Lambda`:               `Λ`,
	`\mu`:                   `μ`,
	`\Mu`:                   `Μ`,
	`\nu`:                   `ν`,
	`\Nu`:                   `Ν`,
	`\xi`:                   `ξ`,
	`\Xi`:                   `Ξ`,
	`\omicron`:              `ο`,
	`\Omicron`:              `Ο`,
	`\pi`:                   `π`,
	`\Pi`:                   `Π`,
	`\rho`:                  `ρ`,
	`\Rho`:                  `Ρ`,
	`\sigma`:                `σ`,
	`\Sigma`:                `Σ`,
	`\tau`:                  `τ`,
	`\Tau`:                  `Τ`,
	`\upsilon`:              `υ`,
	`\Upsilon`:              `Υ`,
	`\phi`:                  `φ`,
	`\Phi`:                  `Φ`,
	`\chi`:                  `χ`,
	`\Chi`:                  `Χ`,
	`\psi`:                  `ψ`,
	`\Psi`:                  `Ψ`,
	`\omega`:                `ω`,
	`\Omega`:                `Ω`,
	`\hbar`:                 `ℏ`,
	`\nabla`:                `∇`,
	`\int`:                  `∫`,
	`\sqrt`:                 `√`,
	`\epsilon `:             `ε`,
	`\digamma`:              `ϝ`,
	`\sum`:                  `Σ`,
	`\prod`:                 `∏`,
	`\oint`:                 `∮`,
	`\arccos`:               `arccos`,
	`\cos`:                  `cos`,
	`\sinh`:                 `sinh`,
	`\arcsin`:               `arcsin`,
	`\cosh`:                 `cosh`,
	`\arctan`:               `arctan`,
	`\tan`:                  `tan`,
	`\cot`:                  `cot`,
	`\sec`:                  `sec`,
	`\log`:                  `log`,
	`\sin`:                  `sin`,
	`\tanh`:                 `tanh`,
	`\ast`:                  `*`,
	`\div `:                 `÷`,
	`\neq`:                  `≠`,
	`\ne`:                   `≠`,
	`\simeq`:                `≃`,
	`\infty`:                `∞`,
	`\partial`:              `∂`,
	`\angle`:                `∠`,
	`\leftarrow`:            `←`,
	`\rightarrow`:           `→`,
	`\times`:                ` × `,
	`\text`:                 ``,
	`\left`:                 ` `,
	`\right`:                ` `,
	`\lim`:                  `limit`,
	`\binom`:                ``,
	`\overline`:             ``,
	`\perp`:                 `⊥`,
	`\mathrm`:               ``,
	`\in`:                   `∈`,
	`\underset`:             ``,
	`\displaystyle`:         ``,
	`\Cdot`:                 `.`,
	`\lceil`:                ``,
	`\rceil`:                ``,
	`\vec`:                  `vec`,
	`\hat`:                  ``,
	`\langle`:               `<`,
	`\rangle`:               `>`,
	`\parallel`:             `∥`,
	`\doteq`:                `≐`,
	`\downarrow`:            `↓`,
	`\emptyset`:             `∅`,
	`\equiv`:                `≡`,
	`\exists`:               `∃`,
	`\forall`:               `∀`,
	`\frown`:                `⌢`,
	`\iff`:                  `⇐⇒`,
	`\hookleftarrow`:        `↩`,
	`\hookrightarrow`:       `↪`,
	`\imath`:                `ı`,
	`\jmath`:                ``,
	`\Join`:                 `⨝`,
	`\leq`:                  `≤`,
	`\geq`:                  `≥`,
	`\ll`:                   `>>`,
	`\longleftarrow`:        `←−`,
	`\longleftrightarrow i`: `←→`,
	`\longrightarrow`:       `−→`,
	`\mho`:                  `℧`,
	`\Re`:                   `R`,
	`\rhd`:                  `✄`,
	`\sqsubset`:             `⊏`,
	`\sqsubseteq`:           `⊑`,
	`\sqsupset`:             `⊐`,
	`\sqsupseteq`:           `⊒`,
	`\cdot`:                 `⋅`,
	`\n`:                    ``,
	`\mu_0`:                 `μ0`,
	`\le`:                   `<`,
	`\ge`:                   `>`,
	`\circ`:                 `∘`,
	`\cup`:                  `∪`,
	`\cap`:                  `∩`,
	`\sim`:                  `∼`,
	`\gt`:                   `>`,
	`\lt`:                   `<`,
}

var LatexCaptureGroupMap = map[string]string{
	`\frac`:  `$1/$2`,
	`\dfrac`: `$1/$2`,
	`\cfrac`: `$1/$2`,
}

var LatexEscapeSymbols = map[string]string{
	`$$`:    ` `,
	`^`:     ``,
	`_`:     ``,
	`$`:     ` `,
	`{`:     `( `,
	`}`:     `) `,
	`[`:     `( `,
	`]`:     `) `,
	`&nbsp`: ``,
	`&#39`:  `'`,
	`&#34`:  `"`,
	`amp`:   ``,
	`:`:     ``,
	`;`:     ``,
	`&gt`:   `>`,
	`&lt`:   `<`,
	`\end`:  ``,
}
