package constants

var MathsTextSymbolMap = map[string]string{
	"alpha":              "α",
	"beta":               "β",
	"chi":                "χ",
	"delta":              "δ",
	"epsilon":            "ε",
	"eta":                "η",
	"gamma":              "γ",
	"iota":               "ι",
	"kappa":              "κ",
	"lambda":             "λ",
	"mu":                 "μ",
	"nu":                 "ν",
	"omega":              "ω",
	"phi":                "φ",
	"pi":                 "π",
	"psi":                "Ψ",
	"rho":                "ρ",
	"sigma":              "σ",
	"tau":                "τ",
	"theta":              "Θ",
	"upsilon":            "Υ",
	"xi":                 "ξ",
	"zeta":               "ζ",
	"integration":        "∫",
	"double integration": "∬",
	"similar":            "~",
	"infinite":           "∞",
	"nabla":              "∇",
	"partial derivative": "∂",
	"forall":             "∀",
	"exists":             "∃",
	"h bar":              "ℏ",
	"mho":                "℧",
	"square root":        "√",
}
